services:

  auth_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGPORT: ${PG_PORT}
    expose:
      - ${PG_PORT}
    ports:
      - ${PG_PORT}:${PG_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB} -p ${PG_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_redis:
    image: redis:7.2.4
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  auth_api:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile.tests
    env_file:
      - .env.test
    ports:
      - "8000:8000"
    depends_on:
      auth_postgres:
        condition: service_healthy
      auth_redis:
        condition: service_healthy
